# -*- coding: utf-8 -*-
"""Aula03-completa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcP3Q4OVr-ZCfpXhnuwNrK1PVV_xxN4k

# Módulo 3

### Estrutura de repetição, loop: "for"
"""

dict_desafio = [
    {"nome": "Maria Silva", "média": 8.9},
    {"nome": "João Santos", "média": 7.5},
    {"nome": "Ana Oliveira", "média": 4.2},
    {"nome": "Pedro Costa", "média": 1.4}
]

n = 0

while n < len(dict_desafio):
    print(dict_desafio[n])
    n += 1

for elemento in dict_desafio:
    print(elemento)

for n in range(5):
    print(n)

for n in range(2, 7):
    print(n)

for n in range(2, 7, 3):
    print(n)

pessoa = {
    "nome": "Fabrício",
    "idade": 19,
    "altura": 1.87
}

print(pessoa)

for chave in pessoa:
    print(chave)

pessoa.items()

pessoa.keys()

pessoa.values()

for chave, valor in pessoa.items():
    print(f"A chave é {chave} e o valor é {valor}.")

for n in range(11):
    if n % 2 == 0:
        print(n)

for n in range(11):
    if n % 3 == 0:
        print(n)

"""### Funções"""

texto1 = "   Fabrício CARRaro  da alura   "
texto2 = "mArIA   aNA    sAntoS   pereiRA"
texto3 = "  PeDRO   alvaRes   cabrAl "
texto4 = "   anA   caroLINa     FerreirA  "
texto5 = "  rObertO    carlOS      OliveiRa  "

texto1.split()

len(texto1.split())

def escreve_texto_corretamente(texto):
    texto_novo = texto.upper()
    lista_de_palavras = texto_novo.split()
    nome_final = " ".join(lista_de_palavras)
    return nome_final

escreve_texto_corretamente(texto1)

escreve_texto_corretamente(texto2)

escreve_texto_corretamente(texto3)

def escreve_texto_corretamente_alternativa(texto):
    print(" ".join(texto.upper().split()))

escreve_texto_corretamente_alternativa(texto1)

salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
    sala_do_aluno = random.choice(lista_de_salas)

    dict_aluno = {
        "nome":nome_do_aluno,
        "sala":sala_do_aluno
    }
    print(dict_aluno)

aloca_alunos_em_salas(texto1, salas_de_aula)

nome_processado = escreve_texto_corretamente(texto1)
aloca_alunos_em_salas(nome_processado, ["Classe 1", "Classe 2", "Classe 3"])

"""Desafio:
<br>
1. Pedir pra uma IA gerar em Python uma lista de 20 emails pra você.
2. Criar uma função que vai receber como argumento/parâmetro uma lista de emails, percorrer essa lista de emails, e, para cada email da lista,
ela irá chamar a IA do Gemini via API e pedir pra ela resumir pra você cada email em apenas 1 linha, definindo o que essa pessoa queria no email
"""

email_bodies = [
    """
    Olá, equipe!

    Gostaria de informar que a reunião de planejamento para o próximo trimestre foi remarcada para a próxima sexta-feira, às 10h.
    Por favor, confirmem sua presença.

    Atenciosamente,
    João Silva
    """,
    """
    Prezados clientes,

    Nossa plataforma passará por uma atualização de sistema na madrugada de sábado para domingo.
    O serviço poderá ficar indisponível por algumas horas. Pedimos desculpas por qualquer transtorno.

    Atenciosamente,
    Equipe de Suporte
    """,
    """
    Oi, Maria!

    Tudo bem? Estou te escrevendo para saber se você recebeu o relatório que te enviei ontem.
    Precisamos fechar a análise até o final da semana. Me avise se precisar de algo.

    Abraços,
    Carlos
    """,
    """
    Caros colaboradores,

    Lembramos que o prazo para a entrega dos holerites de dezembro se encerra na próxima segunda-feira.
    Qualquer dúvida, por favor, entrem em contato com o departamento de RH.

    Obrigado,
    Recursos Humanos
    """,
    """
    Olá,

    Confirmamos o recebimento do seu pedido #12345. Ele já está em processamento e você receberá um novo email
    com o código de rastreamento assim que for enviado.

    Obrigado por comprar conosco!
    """,
    """
    Bom dia,

    Escrevo para formalizar o pedido de férias de 15 dias, com início previsto para o dia 20 de agosto.
    Aguardo a aprovação.

    Obrigado,
    André Costa
    """,
    """
    Olá, Fernando,

    Gostaria de agradecer a sua participação no nosso último webinar.
    Seu feedback foi muito importante para nós. Em anexo, segue o material completo apresentado.

    Atenciosamente,
    Time de Marketing
    """,
    """
    Prezado(a) [Nome do Cliente],

    A sua fatura mensal no valor de R$ [valor] referente aos serviços de [serviço] está disponível.
    Você pode acessá-la e realizar o pagamento através do nosso portal do cliente.

    Atenciosamente,
    Equipe Financeira
    """,
    """
    Oi, Ana!

    Que tal sairmos para almoçar na quarta-feira?
    Pensei naquele restaurante novo que abriu perto do escritório.
    Me avisa se você puder.

    Beijos,
    Lúcia
    """,
    """
    Prezados fornecedores,

    Gostaria de solicitar um orçamento detalhado para a compra de 500 unidades do produto X.
    Aguardamos o retorno o mais breve possível.

    Cordialmente,
    Departamento de Compras
    """,
    """
    Olá, Pedro,

    Recebi seu currículo e achei seu perfil bastante interessante para a vaga de Desenvolvedor Júnior.
    Gostaria de agendar uma entrevista para a próxima semana. Poderia nos informar sua disponibilidade?

    Obrigado,
    Recrutamento e Seleção
    """,
    """
    Bom dia,

    Estamos com problemas técnicos em nossa rede.
    Nossa equipe já está trabalhando para resolver a situação e normalizar o serviço o mais rápido possível.

    Agradecemos a compreensão.
    """,
    """
    Prezado Sr. Antônio,

    Escrevo para confirmar nossa reunião agendada para amanhã, às 14h, em sua sala.
    Estaremos discutindo a proposta de projeto que lhe enviamos.

    Atenciosamente,
    Mariana Fontes
    """,
    """
    Olá,

    Parabéns! Você acaba de ganhar 10% de desconto na sua próxima compra em nossa loja online.
    Use o cupom **DESCONTO10** no checkout.

    Aproveite!
    """,
    """
    Oi, galera!

    A festa de confraternização da empresa será no dia 15 de dezembro, a partir das 19h, no Salão de Eventos.
    Teremos música, comida e muita diversão! Não percam!

    Até lá,
    Comitê de Festas
    """,
    """
    Prezada Sra. Costa,

    Obrigado por entrar em contato. Seu pedido de cancelamento de assinatura foi processado.
    Você receberá uma confirmação separada em breve.

    Qualquer dúvida, estamos à disposição.
    """,
    """
    Boa tarde,

    Gostaria de saber se é possível adiar o prazo de entrega do projeto A para a próxima semana.
    Estamos com alguns contratempos e precisamos de mais tempo para garantir a qualidade final.

    Obrigado,
    Roberto Almeida
    """,
    """
    Olá, equipe de vendas,

    O relatório de desempenho do último mês foi liberado.
    Por favor, analisem os dados e me enviem seus comentários até o final da semana.

    Atenciosamente,
    Diretoria Comercial
    """,
    """
    Prezados pais e responsáveis,

    Lembramos que a reunião de pais será realizada nesta quinta-feira, às 19h, na quadra da escola.
    Sua presença é muito importante.

    Atenciosamente,
    Direção da Escola
    """,
    """
    Olá,

    Convidamos você para nosso próximo workshop sobre Inteligência Artificial, que acontecerá no dia 30 de setembro.
    As vagas são limitadas! Garanta a sua inscrição pelo link: [link para inscrição].

    Esperamos você!
    """,
]

def resumidor_de_emails(lista_de_emails):
    lista_de_resumos = []

    for numero, email in enumerate(lista_de_emails):
        resposta = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas 1 linha,
                        passando o intuito daquele e-mail. Segue o e-mail: {email}"""
            )
        print(f"E-mail {numero + 1}: {resposta.text}")
        lista_de_resumos.append(f"E-mail {numero + 1}: {resposta.text}")
        print("-" * 50)

    return lista_de_resumos

lista_resumos = resumidor_de_emails(email_bodies)

lista_resumos

"""### Rodando um modelo aberto via Groq"""

!pip install -q groq

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

from groq import Groq

client_groq = Groq()

completion = client_groq.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "De que é feito o Sol?"
      }
    ],
    temperature=1, #0 - o menos criativo possível; 2 - o mais criativo possível
    max_completion_tokens=8192,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")