# -*- coding: utf-8 -*-
"""Aula02-completa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177ODspQ7QNJjHsRkhaqTyL8g2_sUNSba

# Módulo 2

### Rodando a sua IA no Google Colab
"""

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY_2')

from google import genai

client = genai.Client()

resposta = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="O que é a Inteligência Artificial?"
    )

print(resposta.text)

"""### Estruturas de Repetição, Loops, Laços"""

print("***************")

n = 1

while n <= 10:
    print("*")
    n = n + 1

chat = client.chats.create(model="gemini-2.5-flash")

resposta = chat.send_message("O que é a Inteligência Artificial?")

print(resposta.text)

resposta = chat.send_message("Quando foi lançado o ChatGPT?")
print(resposta.text)

chat.get_history()

prompt = input("Digite a sua pergunta: ")

while prompt != "fim":
    resposta = chat.send_message(prompt)
    print(resposta.text)
    print("\n")
    prompt = input("Digite a sua pergunta: ")

"""### Estruturas de dados

#### Listas
"""

lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "Juliana Pereira"]
#                      0               1               2              3                4

print(lista_de_nomes[3])

lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

print(lista_de_medias)

print(lista_de_medias[3])

"""Desafio: Crie um código que percorra a lista de médias e some 1 a cada valor, exceto quando o valor passar de 10.0, que aí ele deve parar em 10.0."""

n = 0

while n < 5:
    lista_de_medias[n] = lista_de_medias[n] + 1.0
    if lista_de_medias[n] > 10.0:
        lista_de_medias[n] = 10.0

    n = n + 1

print(lista_de_medias)

len(lista_de_medias)

n = 0

while n < len(lista_de_medias):
    lista_de_medias[n] = lista_de_medias[n] + 1.0
    if lista_de_medias[n] > 10.0:
        lista_de_medias[n] = 10.0

    n = n + 1

print(lista_de_medias)

lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

print(lista_de_medias)

lista_de_medias[len(lista_de_medias) - 1]

lista_de_medias[-1]

lista_de_medias[-2]

"""#### Particionando uma lista"""

lista_de_nomes

lista_de_nomes[1:3]

lista_de_nomes[1:4]

lista_de_nomes[1:]

lista_de_nomes[0:4]

lista_de_nomes[:4]

lista_de_nomes

lista_de_nomes.append("Fábio Carraro")

lista_de_nomes

len(lista_de_nomes)

lista_de_nomes.append("Joana da Silva", "Paulo Silveira")

lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

lista_de_nomes

lista_de_nomes.append(["Márcio Costa", "Natália Pedreira"])

lista_de_nomes

lista_de_nomes[8]

lista_de_nomes[8][0]

lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "Juliana Pereira"]
#                      0               1               2              3                4

lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

lista_de_nomes

lista_de_nomes.remove("Paulo Silveira")

lista_de_nomes

lista_de_nomes.pop()
print(lista_de_nomes)

lista_de_nomes.pop(2)
print(lista_de_nomes)

"""#### Dicionários<br>"chave":valor"""

lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "Juliana Pereira"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

dict_de_nomes_e_medias = {"Maria Silva":8.9,
                         "João Santos":7.5,
                         "Ana Oliveira":4.2,
                         "Pedro Costa":1.4,
                         "Juliana Pereira":9.5}

dict_de_nomes_e_medias["Maria Silva"]

dict_de_nomes_e_medias.get("Maria Silva")

dict_de_nomes_e_medias.pop("Juliana Pereira")

dict_de_nomes_e_medias

dict_de_nomes_e_medias.items()

dict_de_nomes_e_medias.keys()

dict_de_nomes_e_medias.values()

"""Desafio: Usar dicionários de forma que as chaves sejam "nome" e "média", e os valores, sejam os nomes e médias dos alunos"""

dict_desafio = [
    {"nome": "Maria Silva", "média": 8.9},
    {"nome": "João Santos", "média": 7.5},
    {"nome": "Ana Oliveira", "média": 4.2},
    {"nome": "Pedro Costa", "média": 1.4}
]

dict_desafio[0]

dict_desafio[0]["média"]