# -*- coding: utf-8 -*-
"""Aula01-completa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WETmeYAowvalnz1go_KIzTYeBjfdWWEG

# Módulo 1

Começando a Aula de Python
"""

5

print(5)

"""Textos ou palavras são chamados de string"""

print("Olá mundo")

print('Olá mundo')

print("Olá mundo " + "5")

5 + 2

print(5 + 2)

produto1 = 5

print(produto1)

produto2 = 2000

print(produto2)

produto3 = 1

print(produto1 + produto2 + produto3)

nome_do_produto1 = "Macarrão"
nome_do_produto2 = "Celular"
nome_do_produto3 = "Bala"

print(nome_do_produto1 + " " + nome_do_produto2 + " " + nome_do_produto3)

amigos = 5
aluguel = 1000
supermercado = 500
carro = 400

total = aluguel + supermercado + carro

print(total)

aluguel = 900
total = aluguel + supermercado + carro

print(total)

aluguel = aluguel - 100

print(aluguel)

amigos = 6
aluguel = 1000
supermercado = 500
carro = 400

print(amigos)

print(carro * 2)

total_de_carros = carro * 2

print(total_de_carros)

total = aluguel + supermercado + total_de_carros
print(total)

total_por_pessoa = total / amigos
print(total_por_pessoa)

type(aluguel)

type(total_por_pessoa)

type(nome_do_produto1)

pedro_tem_carteira_de_motorista = True
mario_tem_carteira_de_motorista = False

type(mario_tem_carteira_de_motorista)

"""Inicial: "   Fabrício CARRaro   da alura   "<br>
Final: "FABRÍCIO CARRARO DA ALURA"
"""

texto = "   Fabrício CARRaro  da alura   "

print(texto)

print(texto.lower())

print(texto.upper())

print(texto.strip())

print(texto.replace("  ", " "))

print(texto)

print(texto.strip().upper().replace("  ", " "))

print(texto)

texto = texto.strip().upper().replace("  ", " ")
print(texto)

print(texto)

nome = input("Digite o seu nome: ")

print(nome)

idade = input("Digite a sua idade: ")

print(idade)

type(nome)

type(idade)

idade = int(idade)

type(idade)

print("A pessoa se chama " + nome + " e tem " + str(idade) + " anos de idade.")

print(f"A pessoa se chama {nome} e tem {idade} anos de idade.")

"""### Estruturas Condicionais"""

nome = input("Digite o seu nome: ")

idade = int(input("Digite a sua idade: "))

type(idade)

if idade >= 18:
    print(f"O {nome} pode entrar na festa porque ele é maior de idade.")
    print(f"Ele tem {idade} anos de idade.")
else:
    print(f"O {nome} NÃO pode entrar na festa porque ele é menor de idade.")
    print(f"Ele tem {idade} anos de idade.")

media = float(input("Digite a sua média: "))

if media >= 7.0:
    print("Aprovado!")
elif media >= 5.0:
    print("Recuperação!")
else:
    print("Reprovado!")

media = float(input("Digite a sua média: "))

if media < 5.0:
    print("Reprovado!")
elif media >= 5.0 and media < 7.0:
    print("Recuperação!")
else:
    print("Aprovado!")