# -*- coding: utf-8 -*-
"""Aula04-completa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vO1OK8_lwc0FAN75KAR0PGCY6Ra-ozBj

# Módulo 4

### Lendo e escrevendo em arquivos usando Python
"""

with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:
    for resumo in lista_resumos:
        arquivo.write(resumo + "\n")

nova_lista_de_leitura = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        nova_lista_de_leitura.append(linha.strip())

nova_lista_de_leitura

conteudo = ""

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
    conteudo = arquivo.read()

conteudo

nova_lista_de_leitura_2 = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:
    nova_lista_de_leitura_2 = arquivo.readlines()

nova_lista_de_leitura_2

"""### Manipulando dados com Pandas"""

import pandas as pd

df = pd.read_csv("/content/meu_csv.csv")

df.head()

df.tail()

"""Desafio:
1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python [].
2. Ler as perguntas desse arquivo .txt e salvá-las em uma lista Python
3. Obter respostas de um LLM para cada uma.
4. Salvar os resultados em um novo arquivo .csv
5. Ler o arquivo .csv usando Pandas
"""

# Etapa 1
lista_de_perguntas = [
    "De que é feito o Sol?",
    "De que é feito o planeta Saturno?",
    "Qual é a galáxia mais antiga já encontrada?",
    "Qual é a maior estrela já encontrada?",
    "Qual é a estrela mais próxima do Sol?"
]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
    for pergunta in lista_de_perguntas:
        arquivo.write(pergunta + "\n")

# Etapa 2
lista_desafio = []

with open("perguntas.txt", "r", encoding="utf-8") as arquivo:
    for linha in arquivo:
        lista_desafio.append(linha.strip())

print(lista_desafio)

# Etapa 3
lista_de_dicionarios_de_respostas = []

for pergunta in lista_desafio:
    resposta = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"Gere uma resposta muito sucinta para a pergunta: {pergunta}"
        )
    lista_de_dicionarios_de_respostas.append({"pergunta":pergunta, "resposta":resposta.text})

lista_de_dicionarios_de_respostas

# Etapa 4
with open("respostas1.csv", "w", encoding="utf-8") as arquivo:
    arquivo.write("pergunta,resposta\n")
    for pergunta_dict in lista_de_dicionarios_de_respostas:
        arquivo.write(f"{pergunta_dict['pergunta']},{pergunta_dict['resposta']}\n")

df_perguntas_e_respostas = pd.DataFrame(lista_de_dicionarios_de_respostas)

df_perguntas_e_respostas

df_perguntas_e_respostas.to_csv("resposta2.csv", index=False, encoding="utf-8")

# Etapa 5
novo_df = pd.read_csv("resposta2.csv")

novo_df